apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: php
  name: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: php
    spec:
      containers:
      - image: priyatp/php:develop
        name: php
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/symfony
          name: php-claim0
        - mountPath: /var/log
          name: php-claim1
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
      - name: php-claim1
        persistentVolumeClaim:
          claimName: php-claim1
status: {}
