apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: php
  name: php
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    service: php
status:
  loadBalancer: {}
