apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: nginx
  name: web
spec:
  ports:
  - name: "80"
    nodePort: 31000
    port: 80
    targetPort: 80
  selector:
    service: nginx
  type: NodePort
status:
  loadBalancer: {}
